name: Check pre-commit githook, train.py, infer.py
run-name: ${{ github.actor  }} uses GitHub Actions for checking pre-commit and model integration

on: [push]

jobs:
  hooks_job:
    name: My-beautiful-check
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        python-version: ["3.8"]
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout (git clone) repo to docker
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.5.1
          virtualenvs-create: true
          virtualenvs-in-project: true
      - name: Install dependencies
        run: poetry install --no-interaction --no-root
      - name: Install pre-commit
        run: poetry run pre-commit install
      - name: Check all githooks (pre-commit)
        run: poetry run pre-commit run -a
      - name: Check train.py
        run: poetry run python3 mipt_mlops_project_1/train.py
      - name: Check infer.py
        run: poetry run python3 mipt_mlops_project_1/infer.py
      - name: Check Fire interface
        run: poetry run python3 mipt_mlops_project_1/commands.py train
             poetry run python3 mipt_mlops_project_1/commands.py infer
